version: '3.8'
volumes:
  pgdata:
services:
  postgres:
    image: postgres:15.4
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=katalist
      - PGDATA=/var/lib/postgresql/data/pgdata
