version: '0.1'
services:
  postgres:
    image: katalistdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '7432:7432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data