name: Create database image and deploy in Azure Register

on:
  workflow_dispatch:


jobs:
  build-test-deploy-docker:

    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{secrets.ACR_ENDPOINT}}
          username: ${{ secrets.ACR_USERNAME}}
          password: ${{ secrets.ACR_PASSWORD}}
      - name: Build and push docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./docker/database/
          push: true
          tags: katalistdb:latest
          build-args: ${{secrets.POSTGRES_PASSWORD}}
