# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

jobs:
  build-test-deploy-docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{secrets.ACR_ENDPOINT}}
        username: ${{ secrets.ACR_USERNAME}}
        password: ${{ secrets.ACR_PASSWORD}}
    - name: Build and push docker image
      uses: docker/build-push-action@v4.0.0
      with:
         context: .
         push: true
         tags: ${{ secrets.ACR_ENDPOINT }}
  deploy:
    runs-on: ubuntu-latest
    needs:  build-test-deploy-docker   
    permissions:
      id-token: write
      contents: read
    steps:      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CREDENTIALS }}              
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }} 
          images: ${{ secrets.ACR_ENDPOINT }}
      - name: Azure logout
        run:
          az logout
